name: .NET Test (Hizkitza)

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Hizkitza/Hizkitza.sln

    - name: Build solution
      run: dotnet build Hizkitza/Hizkitza.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test Hizkitza/Hizkitza.sln --no-build --verbosity normal --configuration Release